apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dubovsky-andrey/kubernetes-public
    path: apps/prometheus/overlays/test
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
